config/routes.rb
Rails.application.routes.draw do
  #region resources
  resources :type_of_meetings, :meetings,
            :type_of_courses, :church_men, :title_obtaineds, :courses

  resources :admins do
    get 'generate_meeting_report', on: :collection
    post 'upload_meeting_report', on: :collection
    get 'on_change_select_person', on: :collection
    get 'on_change_select_meeting', on: :collection
  end

  resources :courses do
    get 'enrollments', on: :member
  end

  resources :people do
    get 'generate_meeting_report', on: :collection
    post 'upload_meeting_report', on: :collection
    get 'new_express', on: :collection
  end

  resources :user_credentials do
    get 'new_with_linked_person', on: :collection
    post 'create_with_linked_person', on: :collection
  end
  #endregion

  #region setting
  devise_for :users, controllers: {sessions: 'users/sessions', registration: 'users/registration'}
  root 'welcome#index'
  #endregion

  #region restrict

  #endregion


end

app/models/ability.rb
# frozen_string_literal: true

Setting = 1

class Ability
  include CanCan::Ability

  def initialize(user)
    return unless user.present?
    if user.is?(:churchman)
      can :manage, Person, person_id: user.person_id
      can :manage, TitleObtained, code: 1..4
      can :manage, Setting
      can :generate_meeting_assistance_report, TypeOfMeeting, id: user.person.meetings.where(active: true).pluck(:type_of_meeting_id)
    elsif user.is?(:admin)
      can :manage, :all
    end
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  has_one :person, as: :rolable, dependent: :destroy
  accepts_nested_attributes_for :person, allow_destroy: true
  validates_associated :person
end

app/models/church_man.rb
class ChurchMan < ApplicationRecord
  has_one :person, as: :rolable, dependent: :destroy
  accepts_nested_attributes_for :person, allow_destroy: true
  validates :person, presence:true
end

app/models/course.rb
class Course < ApplicationRecord
  belongs_to :type_of_course
  has_many :course_enrollments, dependent: :destroy
  accepts_nested_attributes_for :course_enrollments, reject_if: :all_blank, allow_destroy: true

  validates :start_date,:end_date,
            :name,
            :type_of_course_id,
            :pre_enrollment,:end_enrollment,:min_people,
            :max_people, :amount_by_person,:attendance_control, presence:true

end

app/models/course_enrollment.rb
class CourseEnrollment < ApplicationRecord
  belongs_to :person
  belongs_to :course
end

app/models/course_progress.rb
class CourseProgress < ApplicationRecord
  belongs_to :person
  belongs_to :type_of_course
end

app/models/course_topic.rb
class CourseTopic < ApplicationRecord
  belongs_to :type_of_course
end

app/models/location.rb
class Location < ApplicationRecord
  validates :custom_address,presence: true
end

app/models/meeting.rb
class Meeting < ApplicationRecord
  # Relationships
  belongs_to :type_of_meeting
  belongs_to :person
  belongs_to :location

  # Validations
  validates :name, :start_date_time, :end_date_time, :type_of_meeting, :person, :location, presence: true

  validates :person_id,:type_of_meeting_id,:code, uniqueness: { scope: [:person_id,:type_of_meeting_id,:code]}

  accepts_nested_attributes_for :location, reject_if: :all_blank, allow_destroy: true

  # Callbacks
  before_create do
    self.first_start_date = Date.today
  end

  def full_description
    "#{self.name}- #{self.code}"
  end



end

app/models/my_title.rb
class MyTitle < ApplicationRecord
  belongs_to :title_obtained
  belongs_to :person
end

app/models/person.rb
class Person < ApplicationRecord
  #Relationships
  belongs_to :rolable, polymorphic: true, optional: true
  belongs_to :person_leader, class_name: 'Person', foreign_key: 'person_id', optional: true
  has_many :disciples, class_name: 'Person'
  has_one :user, dependent: :destroy
  has_many :my_titles, dependent: :destroy
  has_many :meetings, dependent: :destroy
  has_many :type_of_meetings, through: :meetings
  has_many :title_obtaineds, through: :my_titles
  has_one :active_my_title, -> {where(active: true)}, class_name: 'MyTitle', foreign_key: 'person_id'

  # Decorators
  accepts_nested_attributes_for :user, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :my_titles, reject_if: :all_blank, allow_destroy: true

  # Validations
  validates :name, :last_name, :sex, presence: true
  validate :check_at_least_one_title

  # Scopes
  scope :possible_attendances_to_meeting?, ->(meeting, leader) {
    type_of_meeting = meeting.type_of_meeting
    prerrequisities = type_of_meeting.pre_attendance_meetings.pluck(:title_obtained_id)
    leader ||= meeting.person
    leader.disciples.joins(:active_my_title).where(my_titles: {title_obtained_id: prerrequisities})
  }
  scope :possible_attendances_to_course?, ->(course, leader) {
    type_of_course = course.type_of_course
    # prerrequisities = type_of_meeting.pre_attendance_meetings.pluck(:title_obtained_id)
    # leader ||= meeting.person
    # leader.disciples.joins(:active_my_title).where(my_titles: {title_obtained_id: prerrequisities})
  }


  def check_at_least_one_title
    unless self.rolable
      unless self.my_titles.find {|mt| mt.active === true}
        errors.add(:active_my_title, 'Selecciona al menos un rol de la persona')
      end
    end
  end


  def is?(role)
    role == self.rolable.class.name.downcase.to_sym
  end

  def full_name
    "#{name.titleize} #{last_name.titleize}"
  end

  def age
    (Date.today.year - self.birthday.year) if self.birthday.presence
  end

  def birthday
    super || Date.today - 18.years
  end

  def self.type_of_sex
    %w(M F)
  end
end

app/models/title_obtained.rb
class TitleObtained < ApplicationRecord
  has_many :pre_attendance_meetings,dependent: :destroy
end

app/models/type_of_course.rb
class TypeOfCourse < ApplicationRecord
  has_many :prerequisites, class_name: 'PrerequisiteCourse',dependent: :destroy
  has_many :prerequisite_type_of_courses, through: :prerequisites, source: :prerequisite_course
  has_many :course_topics, dependent: :destroy
  accepts_nested_attributes_for :prerequisites, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :course_topics, reject_if: :all_blank, allow_destroy: true
end

app/models/type_of_meeting.rb
class TypeOfMeeting < ApplicationRecord
  has_many :pre_attendance_meetings,dependent: :destroy, validate: true
  has_many :title_obtaineds,through: :pre_attendance_meetings
  has_many :meetings, dependent: :destroy
  validates :code, uniqueness: true
  accepts_nested_attributes_for :pre_attendance_meetings, allow_destroy: true, update_only: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :rememberable, :validatable
  belongs_to :person

  def is?(role)
    self.person.is?(role)
  end
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/meetings_helper.rb
module MeetingsHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/admins/_form.html.erb
<%= form_with(model: admin, local: true) do |form| %>
  <% if admin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(admin.errors.count, "error") %> prohibited this admin from being saved:</h2>

      <ul>
        <% admin.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :token %>
    <%= form.text_field :token %>
  </div>

  <div class="field">
    <%= form.label :code %>
    <%= form.number_field :code %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/admins/edit.html.erb
<h1>Editing Admin</h1>

<%= render 'form', admin: @admin %>

<%= link_to 'Show', @admin %> |
<%= link_to 'Back', admins_path %>

app/views/admins/generate_meeting_report.html.erb
<% content_for :breadcrumb do %>
  <li class="breadcrumb-item active" aria-current="page">
    Reporte de Informe Personalizado
  </li>
<% end %>
<%= form_for @header_attendance_meeting, url: upload_meeting_report_admins_path do |f| %>
  <input type="hidden" name="type_of_meeting_code" value="<%= @type_of_meeting.code %>">
  <%= render partial: 'layouts/errors', locals: {errors: @header_attendance_meeting.errors} %>
  <div class="card">
    <div class="card-header">
      <h2>Subir Informe <%= @type_of_meeting.name %></h2>
    </div>
    <div class="card-body">
      <%= render partial: "admins/report_meeting/form", locals: {f: f} %>
    </div>
    <div class="card-footer text-muted">
      <%= f.submit("Guardar Informe", {class: 'btn btn-primary'}) %>
      <%= link_to 'Atrás', root_path, class: 'btn btn-danger' %>
    </div>
  </div>
<% end %>

<% content_for :scripts do %>
  <%= javascript_pack_tag 'main-app/src/admins/generate_meeting_report' %>
<% end %>

app/views/admins/index.html.erb
<% content_for :breadcrumb do  %>
  <li class="breadcrumb-item active" aria-current="page">
    Admins
  </li>
<% end %>

<div class="d-flex position-absolute" style="bottom: 10%; right: 2%">
  <a  href="<%= new_admin_path %>" class="btn shadow btn-lg bg-dark rounded-pill">
    <i class="fas fa-plus text-white"></i>
  </a>
</div>

<div class="row">
  <div class="col shadow-sm">
    <table
      data-toggle="table"
      data-search="true"
      data-show-refresh="true"
      data-show-toggle="true"
    >
      <thead>
      <tr>
        <th>Nombre Completo</th>
        <th>Teléfono</th>
        <th>Dirección</th>
        <th></th>
      </tr>
      </thead>
      <tbody>
      <% @admins.each do |admin| %>
        <% person = admin.person %>
        <tr>
          <td><%= person.full_name %></td>
          <td><%= number_to_phone(person.phone_number) %></td>
          <td><%= person.address %></td>
          <td>
            <a href="#" class="text-info mr-1" data-toggle="tooltip" data-placement="top" title="Tooltip on top">
              <i class="fas fa-info"></i>
            </a>
            <a href="<%= edit_admin_path(person) %>" class="text-primary" data-toggle="tooltip" data-placement="top" title="Tooltip on top">
              <i class="fas fa-edit"></i>
            </a>
            <a href="#" class="text-danger" data-toggle="tooltip" data-placement="top" title="Tooltip on top">
              <i class="fas fa-trash"></i>
            </a>
          </td>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/admins/new.html.erb
<h1>New Admin</h1>

<%= render 'form', admin: @admin %>

<%= link_to 'Back', admins_path %>

app/views/admins/on_change_select_person.js.erb
<%= fields_for @header_attendance_meeting do |f| %>
$('.js-example-basic-single').select2('destroy');
$('#content-select-meetings').html("<%= j (render partial: 'admins/report_meeting/select_meetings', locals: {f:f}) %>");
$('.js-example-basic-single').select2({
    language: "es"
});
$('#header_attendance_meeting_meeting_id').on('select2:select', function (e) {
    var data = e.params.data
    $.ajax({
        type: 'get',
        url: $('#header_attendance_meeting_meeting_id').data('urlChangeMeeting'),
        data: {
            authenticity_token: $('[name="csrf-token"]')[0].content,
            person_id: $('#person_id').val(),
            type_of_meeting_code: $('#person_id').data('typeOfMeetingCode'),
            meeting_id: data.id
        },
        success: function (data) {
            console.log(data);
            if (data.attendance_control) {
                $('#total-attendees-custom').addClass('d-none')
                $('#has-attendance-control').removeClass('d-none')
                $('#table-attendance').bootstrapTable('destroy').bootstrapTable({
                    data: data.attendance_people
                });
            }else{
                $('#total-attendees-custom').removeClass('d-none')
                $('#has-attendance-control').addClass('d-none')
            }
        }
    })
});
<% end %>

app/views/admins/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Token:</strong>
  <%= @admin.token %>
</p>

<p>
  <strong>Code:</strong>
  <%= @admin.code %>
</p>

<%= link_to 'Edit', edit_admin_path(@admin) %> |
<%= link_to 'Back', admins_path %>