config/routes.rb
Rails.application.routes.draw do
  #region resources
  resources :type_of_meetings, :meetings,
            :type_of_courses, :church_men, :title_obtaineds, :courses

  resources :admins do
    get 'generate_meeting_report', on: :collection
    post 'upload_meeting_report', on: :collection
    get 'on_change_select_person', on: :collection
    get 'on_change_select_meeting', on: :collection
  end

  resources :courses do
    get 'enrollments', on: :member
  end

  resources :people do
    get 'generate_meeting_report', on: :collection
    post 'upload_meeting_report', on: :collection
    get 'new_express', on: :collection
  end

  resources :user_credentials do
    get 'new_with_linked_person', on: :collection
    post 'create_with_linked_person', on: :collection
  end
  #endregion

  #region setting
  devise_for :users, controllers: {sessions: 'users/sessions', registration: 'users/registration'}
  root 'welcome#index'
  #endregion

  #region restrict

  #endregion


end

app/models/person.rb
class Person < ApplicationRecord
  #Relationships
  belongs_to :rolable, polymorphic: true, optional: true
  belongs_to :person_leader, class_name: 'Person', foreign_key: 'person_id', optional: true
  has_many :disciples, class_name: 'Person'
  has_one :user, dependent: :destroy
  has_many :my_titles, dependent: :destroy
  has_many :meetings, dependent: :destroy
  has_many :type_of_meetings, through: :meetings
  has_many :title_obtaineds, through: :my_titles
  has_one :active_my_title, -> {where(active: true)}, class_name: 'MyTitle', foreign_key: 'person_id'

  # Decorators
  accepts_nested_attributes_for :user, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :my_titles, reject_if: :all_blank, allow_destroy: true

  # Validations
  validates :name, :last_name, :sex, presence: true
  validate :check_at_least_one_title

  # Scopes
  scope :possible_attendances_to_meeting?, ->(meeting, leader) {
    type_of_meeting = meeting.type_of_meeting
    prerrequisities = type_of_meeting.pre_attendance_meetings.pluck(:title_obtained_id)
    leader ||= meeting.person
    leader.disciples.joins(:active_my_title).where(my_titles: {title_obtained_id: prerrequisities})
  }
  scope :possible_attendances_to_course?, ->(course, leader) {
    type_of_course = course.type_of_course
    # prerrequisities = type_of_meeting.pre_attendance_meetings.pluck(:title_obtained_id)
    # leader ||= meeting.person
    # leader.disciples.joins(:active_my_title).where(my_titles: {title_obtained_id: prerrequisities})
  }


  def check_at_least_one_title
    unless self.rolable
      unless self.my_titles.find {|mt| mt.active === true}
        errors.add(:active_my_title, 'Selecciona al menos un rol de la persona')
      end
    end
  end


  def is?(role)
    role == self.rolable.class.name.downcase.to_sym
  end

  def full_name
    "#{name.titleize} #{last_name.titleize}"
  end

  def age
    (Date.today.year - self.birthday.year) if self.birthday.presence
  end

  def birthday
    super || Date.today - 18.years
  end

  def self.type_of_sex
    %w(M F)
  end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  # before_action :set_person, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource

  #region actions with views
  def index
    @title_breadcrum = "Persona"
    if params[:filter_code]
      @title_obtained = TitleObtained.find_by_code(params[:filter_code])
      if @title_obtained
        @people = @people.joins(my_titles: :title_obtained)
                      .where("title_obtaineds.code = ? and my_titles.active = true", params[:filter_code])
      end
    end

    if current_user.is?(:churchman)
      @people = @people.where(person_id: current_user.person.id)
    end

  end

  def new
    TitleObtained.all.each do |title_obtained|
      title = @person.my_titles.build
      title.title_obtained = title_obtained
    end
    @people = Person.all
  end

  def edit
    @people = Person.all
    unless @person.my_titles.any?
      TitleObtained.all.each do |title_obtained|
        title = @person.my_titles.build
        title.title_obtained = title_obtained
        title.save
      end
    end
  end

  #endregion

  #region logical actions
  def create
    @people = Person.all
    @person = Person.new(person_params)
    TitleObtained.all.each do |title_obtained|
      new_title = @person.my_titles.build
      new_title.title_obtained = title_obtained
      new_title.active = params[:title_obtained_id].to_i === title_obtained.id
      new_title.title_date = Date.today
    end

    respond_to do |format|
      if @person.save
        format.html {redirect_to people_path, notice: 'Person was successfully created.'}
        format.js {
          render(json: [{person_model: @person}])}
      else
        format.js
        format.html {render :new}
      end
    end
  end

  def update
    @person.my_titles.where(active: true).update_all(active: false)
    active_new_title = @person.my_titles.where(title_obtained_id: params[:title_obtained_id]).first
    active_new_title ||= @person.my_titles.build
    active_new_title.title_date = Date.today
    active_new_title.active = true
    active_new_title.save
    respond_to do |format|
      if @person.update(person_params)
        format.html {redirect_to people_path, notice: 'Person was successfully updated.'}
      else
        @people = Person.all
        format.html {render :edit}
      end
    end
  end

  def destroy;
  end

  def generate_meeting_report
    # @type_of_meeting = TypeOfMeeting.find_by_code(params[:type_of_meeting_code])
    # @meeting = current_user.person.meetings.where(type_of_meeting_id: @type_of_meeting.id).first
    @header_attendance_meeting = HeaderAttendanceMeeting.new
    @people = Person.all
    @meetings = []
  end

  def upload_meeting_report

  end

  def new_express
    @person = Person.new
    TitleObtained.all.each do |title_obtained|
      title = @person.my_titles.build
      title.title_obtained = title_obtained
    end
    @people = Person.all

    respond_to do |format|
      format.js
    end
  end

  def generate_meeting_report
    @attendance_people = []
    @type_of_meeting = TypeOfMeeting.find_by_code(params[:type_of_meeting_code])
    @meeting = current_user.person.meetings.where(type_of_meeting: @type_of_meeting, active: true).first
    @header_attendance_meeting = HeaderAttendanceMeeting.new(meeting: @meeting)
    @attendance_people = Person.possible_attendances_to_meeting?(@meeting, current_user.person).order(created_at: :desc)
  end

  def upload_meeting_report
    @attendance_people = []
    @type_of_meeting = TypeOfMeeting.find_by_code(params[:type_of_meeting_code])
    @header_attendance_meeting = HeaderAttendanceMeeting.new(header_attendance_params)
    @person = current_user.person
    @meeting = Meeting.find(@header_attendance_meeting.meeting_id)
    @attendance_people = Person.possible_attendances_to_meeting?(@meeting, @person).order(created_at: :desc)
    if @header_attendance_meeting.meeting_id and @person
      if params[:attendances].present?
        params[:attendances].each do |k, v|
          person_attendance_meeting = @header_attendance_meeting.person_attendance_meetings.build
          person_attendance_meeting.person_id = k
          person_attendance_meeting.attended = true
        end
      end
    end
    respond_to do |format|
      if @header_attendance_meeting.save
        format.html {redirect_to root_path, notice: 'Uploaded new meeting report'}
      else
        format.html {
          render :generate_meeting_report
        }
      end
    end
  end

  #endregion

  private

  def header_attendance_params
    params.require(:header_attendance_meeting)
        .permit(:id, :topic, :attendance_date, :offerings, :prayer, :meeting_id, :total_attendees)
  end

  def set_person
    @person = Person.find(params[:id])
  end

  def person_params
    params_with_leader = params.require(:person)
                             .permit(:name, :last_name, :address, :birthday, :phone_number, :ci, :sex, :person_id)
    unless current_user.is?(:admin)
      params_with_leader = params_with_leader.merge({person_id: current_user.person_id})
    end
    params_with_leader

  end

end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/people/_form.html.erb
<div class="form-row">
  <div class="form-group col-md-6">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control', placeholder: 'Nombres' %>
  </div>
  <div class="form-group col-md-6">
    <%= f.label :last_name %>
    <%= f.text_field :last_name, class: 'form-control', placeholder: 'Apellidos' %>
  </div>
</div>
<div class="form-row">
  <div class="form-group col">
    <%= f.label :address %>
    <%= f.text_field :address, class: 'form-control', placeholder: 'Dirección' %>
  </div>
  <% if current_user.is?(:admin) %>
  <div class="form-group col">
    <%= f.label :person_id %>
    <%= f.select :person_id, @people.collect{|c| ["#{c.full_name} (#{c.active_my_title.try(:title_obtained).try(:name)})", c.id]}, {prompt: 'Ninguna'}, { style: 'width: 100%',class: 'custom-select js-example-basic-single'} %>
  </div>
  <% end %>

</div>
<div class="form-row">
  <div class="form-group col-md-4">
    <%= f.label :birthday %>
    <%= f.date_field :birthday, class: 'custom-select mr-sm-2', placeholder: 'Fecha de Nac.' %>
  </div>
  <div class="form-group col-md-4">
    <%= f.label :phone_number %>
    <%= f.telephone_field :phone_number, class: 'form-control', placeholder: 'Dirección' %>
  </div>
  <div class="form-group col-md-4">
    <%= f.label :ci %>
    <%= f.text_field :ci, class: 'form-control', placeholder: 'Cédula de Identidad' %>
    <small class="text-muted">3232323 SC</small>
  </div>
</div>
<div class="form-group">
  <% sex = f.object.sex %>
  <%= f.label :sex, 'Sexo'%>
  <%= f.label :sex, 'M'%>
  <%= f.radio_button :sex, 'M', :checked => sex === 'M' %>
  <%= f.label :sex, 'F'%>
  <%= f.radio_button :sex, 'F', :checked => sex === 'F'%>
</div>

<div class="form-row">
  <div class="form-group col">
    <label for="exampleFormControlSelect1">
      cualidades de la persona a registrar ?
    </label>
    <%= f.fields_for :my_titles do |tf| %>
      <div class="form-check form-check-inline">
        <label class="form-check-label" >
          <%= tf.object.title_obtained.try :name %>
        </label>
        <input type="radio"
               <%= tf.object.active ? 'checked':nil %>
               name="title_obtained_id" value="<%= tf.object.title_obtained_id %>">
      </div>
    <% end %>
    <small class="text-muted">selecciona uno para ingresar la cualidad actual</small>
  </div>
</div>

app/views/people/_form_express.html.erb
<%= form_for @person, url: people_path, remote: true do |f| %>
  <div class="modal fade bd-example-modal-lg" id="new-express-person" tabindex="-1" role="dialog" aria-labelledby="exampleModalScrollableTitle" aria-hidden="true">
    <div class="modal-dialog modal-lg modal-dialog-scrollable" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalScrollableTitle">Nueva Persona</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <%= render partial: 'layouts/errors', locals: {errors: @person.errors }  %>
          <div class="form-row">
            <div class="form-group col-md-6">
              <%= f.label :name %>
              <%= f.text_field :name, class: 'form-control', placeholder: 'Nombres' %>
            </div>
            <div class="form-group col-md-6">
              <%= f.label :last_name %>
              <%= f.text_field :last_name, class: 'form-control', placeholder: 'Apellidos' %>
            </div>
          </div>
          <div class="form-row">
            <div class="form-group col">
              <%= f.label :address %>
              <%= f.text_field :address, class: 'form-control', placeholder: 'Dirección' %>
            </div>
            <% if current_user.is?(:admin) %>
              <div class="form-group col">
                <%= f.label :person_id %>
                <%= f.select :person_id, @people.collect {|c| ["#{c.full_name} (#{c.active_my_title.try(:title_obtained).try(:name)})", c.id]}, {prompt: 'Ninguna'}, {style: 'width: 100%', class: 'custom-select js-example-basic-single'} %>
              </div>
            <% end %>
          </div>
          <div class="form-row">
            <div class="form-group col-md-4">
              <%= f.label :birthday %>
              <%= f.date_field :birthday, class: 'custom-select mr-sm-2', placeholder: 'Fecha de Nac.' %>
            </div>
            <div class="form-group col-md-4">
              <%= f.label :phone_number %>
              <%= f.telephone_field :phone_number, class: 'form-control', placeholder: 'Dirección' %>
            </div>
            <div class="form-group col-md-4">
              <%= f.label :ci %>
              <%= f.text_field :ci, class: 'form-control', placeholder: 'Cédula de Identidad' %>
              <small class="text-muted">3232323 SC</small>
            </div>
          </div>
          <div class="form-group">
            <% sex = f.object.sex %>
            <%= f.label :sex, 'Sexo' %>
            <%= f.label :sex, 'M' %>
            <%= f.radio_button :sex, 'M', :checked => sex === 'M' %>
            <%= f.label :sex, 'F' %>
            <%= f.radio_button :sex, 'F', :checked => sex === 'F' %>
          </div>

          <div class="form-row">
            <div class="form-group col">
              <label for="exampleFormControlSelect1">
                cualidades de la persona a registrar ?
              </label>
              <%= f.fields_for :my_titles do |tf| %>
                <div class="form-check form-check-inline">
                  <label class="form-check-label">
                    <%= tf.object.title_obtained.try :name %>
                  </label>
                  <input type="radio"
                         <%= tf.object.active ? 'checked' : nil %>
                         name="title_obtained_id" value="<%= tf.object.title_obtained_id %>">
                </div>
              <% end %>
              <small class="text-muted">selecciona uno para ingresar la cualidad actual</small>
            </div>
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
          <%= f.submit('Guardar Persona', class: 'btn btn-dark') %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/people/create.html.erb
Crear Persona

app/views/people/create.js.erb
$('div.modal-backdrop').remove();
<% unless @person.valid? %>
<%= fields_for @person do |f| %>
$('#hold-modal').html("<%= j (render partial: 'people/form_express', locals: {f:f}) %>");
<% end %>
$('.js-example-basic-single').select2({
    language: "es"
});
$('#new-express-person').modal('show');
<% end %>

app/views/people/edit.html.erb
<% content_for :breadcrumb do  %>
  <li class="breadcrumb-item active" aria-current="page">
    Editar Persona
  </li>
<% end %>

<div class="card">
  <div class="card-header">
    <h2>Rellena el Formulario</h2>
    <small class="text-muted">Cualquier persona registrada estará bajo su liderazgo</small>
  </div>
  <div class="card-body">
    <%= form_for @person, url: person_path do |f| %>
      <%= render partial: 'layouts/errors', locals: {errors: @person.errors }  %>
      <%= render partial: 'form', locals: {person: @person, f: f} %>
      <%= f.submit("Editar",{class: 'btn btn-primary'})%>
      <%= link_to 'Atrás', people_path, class: 'btn btn-danger' %>
    <% end %>
  </div>
</div>

<% content_for :scripts do %>
  <%= javascript_pack_tag 'main-app/src/people/edit'%>
<% end %>

app/views/people/generate_meeting_report.html.erb
<% content_for :breadcrumb do %>
  <li class="breadcrumb-item active" aria-current="page">
    Reporte de Informe Personalizado
  </li>
<% end %>
<%= form_for @header_attendance_meeting, url: upload_meeting_report_people_path do |f| %>
  <input type="hidden" name="type_of_meeting_code" value="<%= @type_of_meeting.code %>">
  <%= f.hidden_field :meeting_id %>
  <%= render partial: 'layouts/errors', locals: {errors: @header_attendance_meeting.errors} %>
  <div class="card">
    <div class="card-header">
      <h2>Subir Informe <%= @type_of_meeting.name %></h2>
    </div>
    <div class="card-body">
      <%= render partial: "people/report_meeting/form", locals: {f: f} %>
    </div>
    <div class="card-footer text-muted">
      <%= f.submit("Guardar Informe", {class: 'btn btn-primary'}) %>
      <%= link_to 'Atrás', root_path, class: 'btn btn-danger' %>
    </div>
  </div>
<% end %>

<% content_for :scripts do %>
  <%= javascript_pack_tag 'main-app/src/people/generate_meeting_report' %>
<% end %>

app/views/people/index.html.erb
<% content_for :breadcrumb do  %>
  <li class="breadcrumb-item active" aria-current="page">
    Listado de <%= @title_obtained.try(:name).try(:titleize).try(:pluralize) %>
  </li>
<% end %>

<div class="d-flex position-absolute" style="bottom: 10%; right: 2%">
  <a  href="<%= new_person_path %>" class="btn shadow btn-lg bg-dark rounded-pill">
    <i class="fas fa-plus text-white"></i>
  </a>
</div>

<div class="row">
  <div class="col shadow-sm">
    <table
      data-toggle="table"
      data-search="true"
      data-show-refresh="true"
      data-show-toggle="true"
    >
      <thead>
      <tr>
        <th>Nombre Completo</th>
        <th>Teléfono</th>
        <th>Dirección</th>
        <th></th>
      </tr>
      </thead>
      <tbody>
      <% @people.each do |person| %>
        <tr>
          <td><%= person.full_name %></td>
          <td><%= number_to_phone(person.phone_number) %></td>
          <td><%= person.address %></td>
          <td>
            <a href="#" class="text-info mr-1" data-toggle="tooltip" data-placement="top" title="Tooltip on top">
              <i class="fas fa-info"></i>
            </a>
            <a href="<%= edit_person_path(person) %>" class="text-primary" data-toggle="tooltip" data-placement="top" title="Tooltip on top">
              <i class="fas fa-edit"></i>
            </a>
            <a href="#" class="text-danger" data-toggle="tooltip" data-placement="top" title="Tooltip on top">
              <i class="fas fa-trash"></i>
            </a>
          </td>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/people/new.html.erb
<% content_for :breadcrumb do  %>
  <li class="breadcrumb-item active" aria-current="page">
    Nueva Persona
  </li>
<% end %>

<div class="card">
  <div class="card-header">
    <h2>Rellena el Formulario</h2>
    <small class="text-muted">Cualquier persona registrada estará bajo su liderazgo</small>
  </div>
  <div class="card-body">
    <%= form_for @person, url: people_path do |f| %>
      <%= render partial: 'layouts/errors', locals: {errors: @person.errors }  %>
      <%= render partial: 'form', locals: {person: @person, f: f} %>
      <%= f.submit("Crear",{class: 'btn btn-primary'})%>
      <%= link_to 'Atrás', people_path, class: 'btn btn-danger' %>
    <% end %>
  </div>
</div>

<% content_for :scripts do %>
  <%= javascript_pack_tag 'main-app/src/people/edit'%>
<% end %>

app/views/people/new_express.js.erb
<%= fields_for @person do |f| %>
$('#hold-modal').html("<%= j (render partial: 'people/form_express', locals: {f:f}) %>");
<% end %>
$('.js-example-basic-single').select2({
    language: "es"
});


$('#new-express-person').modal('show');