config/routes.rb
Rails.application.routes.draw do
  #region resources
  resources :type_of_meetings, :meetings,
            :type_of_courses, :church_men, :title_obtaineds, :courses

  resources :admins do
    get 'generate_meeting_report', on: :collection
    post 'upload_meeting_report', on: :collection
    get 'on_change_select_person', on: :collection
    get 'on_change_select_meeting', on: :collection
  end

  resources :courses do
    get 'enrollments', on: :member
  end

  resources :people do
    get 'generate_meeting_report', on: :collection
    post 'upload_meeting_report', on: :collection
    get 'new_express', on: :collection
  end

  resources :user_credentials do
    get 'new_with_linked_person', on: :collection
    post 'create_with_linked_person', on: :collection
  end
  #endregion

  #region setting
  devise_for :users, controllers: {sessions: 'users/sessions', registration: 'users/registration'}
  root 'welcome#index'
  #endregion

  #region restrict

  #endregion


end

app/models/type_of_meeting.rb
class TypeOfMeeting < ApplicationRecord
  has_many :pre_attendance_meetings,dependent: :destroy, validate: true
  has_many :title_obtaineds,through: :pre_attendance_meetings
  has_many :meetings, dependent: :destroy
  validates :code, uniqueness: true
  accepts_nested_attributes_for :pre_attendance_meetings, allow_destroy: true, update_only: true
end

app/controllers/type_of_meetings_controller.rb
class TypeOfMeetingsController < ApplicationController
  before_action :set_type_of_meeting, only: [:show, :edit, :update, :destroy]

  # GET /type_of_meetings
  # GET /type_of_meetings.json
  def index
    @type_of_meetings = TypeOfMeeting.all
  end

  # GET /type_of_meetings/1
  # GET /type_of_meetings/1.json
  def show
  end

  # GET /type_of_meetings/new
  def new
    @type_of_meeting = TypeOfMeeting.new
  end

  # GET /type_of_meetings/1/edit
  def edit
    @title_obtaineds = TitleObtained.all
  end

  # POST /type_of_meetings
  # POST /type_of_meetings.json
  def create
    @type_of_meeting = TypeOfMeeting.new(type_of_meeting_params)

    respond_to do |format|
      if @type_of_meeting.save
        format.html {redirect_to @type_of_meeting, notice: 'Type of meeting was successfully created.'}
        format.json {render :show, status: :created, location: @type_of_meeting}
      else
        format.html {render :new}
        format.json {render json: @type_of_meeting.errors, status: :unprocessable_entity}
      end
    end
  end

  # PATCH/PUT /type_of_meetings/1
  # PATCH/PUT /type_of_meetings/1.json
  def update
    @title_obtaineds = TitleObtained.all
    respond_to do |format|
      if @type_of_meeting.update(type_of_meeting_params.merge(pre_attendance_meetings_attributes: pre_attendance_meeting_params))
        format.html {redirect_to @type_of_meeting, notice: 'Type of meeting was successfully updated.'}
        format.json {render :show, status: :ok, location: @type_of_meeting}
      else
        format.html {render :edit}
        format.json {render json: @type_of_meeting.errors, status: :unprocessable_entity}
      end
    end
  end

  # DELETE /type_of_meetings/1
  # DELETE /type_of_meetings/1.json
  def destroy
    @type_of_meeting.destroy
    respond_to do |format|
      format.html {redirect_to type_of_meetings_url, notice: 'Type of meeting was successfully destroyed.'}
      format.json {head :no_content}
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_type_of_meeting
    @type_of_meeting = TypeOfMeeting.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def type_of_meeting_params
    params.require(:type_of_meeting).except(:title_obtained_ids).permit(:name, :description, :code,
                                            pre_attendance_meetings_attributes:
                                                [:title_obtained_id]
    )

  end

  def pre_attendance_meeting_params
    pre_attendance = []
    @type_of_meeting.title_obtaineds.destroy_all
    params[:type_of_meeting][:title_obtained_ids].each do |title_obtained_id,index|
      unless title_obtained_id.blank?
        pre_attendance << {title_obtained_id: title_obtained_id }
      end
    end
    pre_attendance
  end

end

app/helpers/type_of_meetings_helper.rb
module TypeOfMeetingsHelper
end

app/views/type_of_meetings/_form.html.erb
<div class="form-row">
  <div class="form-group col-md-6">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control', placeholder: 'Nombre de Reunión' %>
  </div>
  <div class="form-group col-md-6">
    <%= f.label :description %>
    <%= f.text_field :description, class: 'form-control', placeholder: 'Descripción' %>
  </div>
</div>
<div class="form-group">
  <%= f.label :code %>
  <%= f.number_field :code, class: 'form-control', placeholder: 'Código' %>
</div>

app/views/type_of_meetings/_form_edit.html.erb
<div class="form-row">
  <div class="form-group col-md-6">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control', placeholder: 'Nombre de Reunión' %>
  </div>
  <div class="form-group col-md-6">
    <%= f.label :description %>
    <%= f.text_field :description, class: 'form-control', placeholder: 'Descripción' %>
  </div>
</div>
<div class="form-row">
  <div class="form-group col">
    <label for="exampleFormControlSelect1">
      Requisito para Asistir ?
    </label>
    <%= f.select :title_obtained_ids, @title_obtaineds.collect{|c| [c.name, c.id]}, {}, {multiple: true,class: 'custom-select'} %>
  </div>
</div>

app/views/type_of_meetings/edit.html.erb
<% content_for :breadcrumb do  %>
  <li class="breadcrumb-item active" aria-current="page">
    Editar Tipo de Reunión
  </li>
<% end %>

<div class="card">
  <div class="card-header">
    Rellena el Formulario
  </div>
  <div class="card-body">
    <fieldset>
    <%= form_for @type_of_meeting, url: type_of_meeting_path, class: 'was-validated' do |f| %>
      <%= render partial: 'layouts/errors', locals: {errors: @type_of_meeting.errors }  %>
      <%= render partial: 'form_edit', locals: {type_of_meeting: @type_of_meeting, f: f} %>
      <div>
        <%= f.submit("Editar",{class: 'btn btn-primary'})%>
        <%= link_to 'Atrás', type_of_meetings_path, class: 'btn btn-danger' %>
      </div>
    <% end %>
    </fieldset>
  </div>
</div>

<% content_for :scripts do %>
  <%= javascript_pack_tag 'main-app/src/type_of_meetings/edit'%>
<% end %>

app/views/type_of_meetings/index.html.erb
<% content_for :breadcrumb do  %>
  <li class="breadcrumb-item active" aria-current="page">
    Reuniones
  </li>
<% end %>

<div class="d-flex position-absolute" style="bottom: 10%; right: 2%">
  <a  href="<%= new_type_of_meeting_path %>" class="btn shadow btn-lg bg-dark rounded-pill">
    <i class="fas fa-plus text-white"></i>
  </a>
</div>

<div class="row">
  <div class="col shadow-sm">
    <table
      data-toggle="table"
      data-search="true"
      data-show-refresh="true"
      data-show-toggle="true"
    >
      <thead>
      <tr>
        <th>Reunión</th>
        <th>Descripción</th>
        <th>Acción</th>
      </tr>
      </thead>
      <tbody>
      <% @type_of_meetings.each do |type_of_meeting| %>
        <tr>
          <td><%= type_of_meeting.name %></td>
          <td><%= type_of_meeting.description %></td>
          <td>
            <a href="<%= type_of_meeting_path(type_of_meeting) %>" class="text-info mr-1" data-toggle="tooltip" data-placement="top" title="Tooltip on top">
              <i class="fas fa-eye"></i>
            </a>
            <a href="<%= edit_type_of_meeting_path(type_of_meeting)%>" class="text-primary" data-toggle="tooltip" data-placement="top" title="Tooltip on top">
              <i class="fas fa-edit"></i>
            </a>
            <%= link_to type_of_meeting, method: :delete,"title":"Tooltip on top", "data-placement:":"top","data-toggle": "tooltip" ,class: 'text-danger', data: { confirm: 'Are you sure?' }  do %>
              <i class="fas fa-trash"></i>
            <% end %>
          </td>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/type_of_meetings/new.html.erb
<% content_for :breadcrumb do  %>
  <li class="breadcrumb-item active" aria-current="page">
    Nuevo Tipo de Reunión
  </li>
<% end %>

<div class="card">
  <div class="card-header">
    Rellena el Formulario
  </div>
  <div class="card-body">
    <%= form_for @type_of_meeting, url: type_of_meetings_path do |f| %>
      <%= render partial: 'layouts/errors', locals: {errors: @type_of_meeting.errors }  %>
      <%= render partial: 'form', locals: {type_of_meeting: @type_of_meeting, f: f} %>
      <%= f.submit("Crear",{class: 'btn btn-primary'})%>
      <%= link_to 'Atrás', type_of_meetings_path, class: 'btn btn-danger' %>
    <% end %>
  </div>
</div>

app/views/type_of_meetings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @type_of_meeting.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @type_of_meeting.description %>
</p>

<p>
  <strong>Code:</strong>
  <%= @type_of_meeting.code %>
</p>

<%= link_to 'Edit', edit_type_of_meeting_path(@type_of_meeting) %> |
<%= link_to 'Back', type_of_meetings_path %>