config/routes.rb
Rails.application.routes.draw do
  #region resources
  resources :type_of_meetings, :meetings,
            :type_of_courses, :church_men, :title_obtaineds, :courses

  resources :admins do
    get 'generate_meeting_report', on: :collection
    post 'upload_meeting_report', on: :collection
    get 'on_change_select_person', on: :collection
    get 'on_change_select_meeting', on: :collection
  end

  resources :courses do
    get 'enrollments', on: :member
  end

  resources :people do
    get 'generate_meeting_report', on: :collection
    post 'upload_meeting_report', on: :collection
    get 'new_express', on: :collection
  end

  resources :user_credentials do
    get 'new_with_linked_person', on: :collection
    post 'create_with_linked_person', on: :collection
  end
  #endregion

  #region setting
  devise_for :users, controllers: {sessions: 'users/sessions', registration: 'users/registration'}
  root 'welcome#index'
  #endregion

  #region restrict

  #endregion


end

app/models/ability.rb
# frozen_string_literal: true

Setting = 1

class Ability
  include CanCan::Ability

  def initialize(user)
    return unless user.present?
    if user.is?(:churchman)
      can :manage, Person, person_id: user.person_id
      can :manage, TitleObtained, code: 1..4
      can :manage, Setting
      can :generate_meeting_assistance_report, TypeOfMeeting, id: user.person.meetings.where(active: true).pluck(:type_of_meeting_id)
    elsif user.is?(:admin)
      can :manage, :all
    end
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  has_one :person, as: :rolable, dependent: :destroy
  accepts_nested_attributes_for :person, allow_destroy: true
  validates_associated :person
end

app/models/church_man.rb
class ChurchMan < ApplicationRecord
  has_one :person, as: :rolable, dependent: :destroy
  accepts_nested_attributes_for :person, allow_destroy: true
  validates :person, presence:true
end

app/models/course.rb
class Course < ApplicationRecord
  belongs_to :type_of_course
  has_many :course_enrollments, dependent: :destroy
  accepts_nested_attributes_for :course_enrollments, reject_if: :all_blank, allow_destroy: true

  validates :start_date,:end_date,
            :name,
            :type_of_course_id,
            :pre_enrollment,:end_enrollment,:min_people,
            :max_people, :amount_by_person,:attendance_control, presence:true

end

app/models/course_enrollment.rb
class CourseEnrollment < ApplicationRecord
  belongs_to :person
  belongs_to :course
end

app/models/course_progress.rb
class CourseProgress < ApplicationRecord
  belongs_to :person
  belongs_to :type_of_course
end

app/models/course_topic.rb
class CourseTopic < ApplicationRecord
  belongs_to :type_of_course
end

app/models/location.rb
class Location < ApplicationRecord
  validates :custom_address,presence: true
end

app/models/meeting.rb
class Meeting < ApplicationRecord
  # Relationships
  belongs_to :type_of_meeting
  belongs_to :person
  belongs_to :location

  # Validations
  validates :name, :start_date_time, :end_date_time, :type_of_meeting, :person, :location, presence: true

  validates :person_id,:type_of_meeting_id,:code, uniqueness: { scope: [:person_id,:type_of_meeting_id,:code]}

  accepts_nested_attributes_for :location, reject_if: :all_blank, allow_destroy: true

  # Callbacks
  before_create do
    self.first_start_date = Date.today
  end

  def full_description
    "#{self.name}- #{self.code}"
  end



end

app/models/my_title.rb
class MyTitle < ApplicationRecord
  belongs_to :title_obtained
  belongs_to :person
end

app/models/person.rb
class Person < ApplicationRecord
  #Relationships
  belongs_to :rolable, polymorphic: true, optional: true
  belongs_to :person_leader, class_name: 'Person', foreign_key: 'person_id', optional: true
  has_many :disciples, class_name: 'Person'
  has_one :user, dependent: :destroy
  has_many :my_titles, dependent: :destroy
  has_many :meetings, dependent: :destroy
  has_many :type_of_meetings, through: :meetings
  has_many :title_obtaineds, through: :my_titles
  has_one :active_my_title, -> {where(active: true)}, class_name: 'MyTitle', foreign_key: 'person_id'

  # Decorators
  accepts_nested_attributes_for :user, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :my_titles, reject_if: :all_blank, allow_destroy: true

  # Validations
  validates :name, :last_name, :sex, presence: true
  validate :check_at_least_one_title

  # Scopes
  scope :possible_attendances_to_meeting?, ->(meeting, leader) {
    type_of_meeting = meeting.type_of_meeting
    prerrequisities = type_of_meeting.pre_attendance_meetings.pluck(:title_obtained_id)
    leader ||= meeting.person
    leader.disciples.joins(:active_my_title).where(my_titles: {title_obtained_id: prerrequisities})
  }
  scope :possible_attendances_to_course?, ->(course, leader) {
    type_of_course = course.type_of_course
    # prerrequisities = type_of_meeting.pre_attendance_meetings.pluck(:title_obtained_id)
    # leader ||= meeting.person
    # leader.disciples.joins(:active_my_title).where(my_titles: {title_obtained_id: prerrequisities})
  }


  def check_at_least_one_title
    unless self.rolable
      unless self.my_titles.find {|mt| mt.active === true}
        errors.add(:active_my_title, 'Selecciona al menos un rol de la persona')
      end
    end
  end


  def is?(role)
    role == self.rolable.class.name.downcase.to_sym
  end

  def full_name
    "#{name.titleize} #{last_name.titleize}"
  end

  def age
    (Date.today.year - self.birthday.year) if self.birthday.presence
  end

  def birthday
    super || Date.today - 18.years
  end

  def self.type_of_sex
    %w(M F)
  end
end

app/models/title_obtained.rb
class TitleObtained < ApplicationRecord
  has_many :pre_attendance_meetings,dependent: :destroy
end

app/models/type_of_course.rb
class TypeOfCourse < ApplicationRecord
  has_many :prerequisites, class_name: 'PrerequisiteCourse',dependent: :destroy
  has_many :prerequisite_type_of_courses, through: :prerequisites, source: :prerequisite_course
  has_many :course_topics, dependent: :destroy
  accepts_nested_attributes_for :prerequisites, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :course_topics, reject_if: :all_blank, allow_destroy: true
end

app/models/type_of_meeting.rb
class TypeOfMeeting < ApplicationRecord
  has_many :pre_attendance_meetings,dependent: :destroy, validate: true
  has_many :title_obtaineds,through: :pre_attendance_meetings
  has_many :meetings, dependent: :destroy
  validates :code, uniqueness: true
  accepts_nested_attributes_for :pre_attendance_meetings, allow_destroy: true, update_only: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :rememberable, :validatable
  belongs_to :person

  def is?(role)
    self.person.is?(role)
  end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: [:show, :edit, :update, :destroy, :enrollments]
  def index
    @courses = Course.all
  end

  def show
  end

  def new
    @course = Course.new
    @type_of_courses = TypeOfCourse.all
  end

  def create
    @type_of_courses = TypeOfCourse.all
    @course = Course.new(course_params)
    respond_to do |format|
      if @course.save
        format.html { redirect_to @course, notice: 'course was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def edit
    @type_of_courses = TypeOfCourse.all
  end

  def update
    @type_of_courses = TypeOfCourse.all
    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to @course, notice: 'course was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
  end

  def enrollments
  end

  private
  def set_course
    @course = Course.find(params[:id])
  end

  def course_params
    params.require(:course).permit(:id,:start_date,:end_date,
                                   :name,
                                   :type_of_course_id,
                                   :total_attendes,:total_people_inscription,
                                   :pre_enrollment,:end_enrollment,
                                   :min_people, :max_people,
                                   :amount_by_person,:attendance_control)
  end
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/church_men_helper.rb
module ChurchMenHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/meetings_helper.rb
module MeetingsHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/courses/_form.html.erb
<div class="form-row">
  <div class="form-group col-md-6">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control', placeholder: 'Título del Curso' %>
  </div>
  <div class="form-group col-md-6">
    <%= f.label :type_of_course_id %>
    <%= f.select :type_of_course_id, @type_of_courses.collect{|c| [c.name, c.id]}, {prompt: 'Ninguno'}, { class: 'custom-select'} %>
  </div>
  <div class="form-group col-md-6">
    <%= f.label :start_date %>
    <%= f.date_field :start_date, min: Date.today ,class: 'form-control' %>
  </div>
  <div class="form-group col-md-6">
    <%= f.label :end_date %>
    <%= f.date_field :end_date, min: Date.today, class: 'form-control'%>
  </div>
  <div class="form-group col-md-6">
    <%= f.label :pre_enrollment %>
    <%= f.date_field :pre_enrollment, min: Date.today ,class: 'form-control' %>
  </div>
  <div class="form-group col-md-6">
    <%= f.label :end_enrollment %>
    <%= f.date_field :end_enrollment, min: Date.today, class: 'form-control' %>
  </div>
  <div class="form-group col-md-4">
    <%= f.label :min_people %>
    <%= f.number_field :min_people, class: 'form-control' %>
  </div>

  <div class="form-group col-md-4">
    <%= f.label :max_people %>
    <%= f.number_field :max_people, class: 'form-control' %>
  </div>


  <div class="form-group col-md-4">
    <%= f.label :amount_by_person %>
    <%= f.number_field :amount_by_person, class: 'form-control' %>
  </div>

  <div class="form-group col-md-12 d-flex align-items-center">
    <div class="form-check">
      <%= f.check_box :attendance_control, class: 'form-check-input' %>
      <%= f.label :attendance_control, class: 'form-check-label' %>
    </div>
  </div>
</div>

app/views/courses/edit.html.erb
<% content_for :breadcrumb do  %>
  <li class="breadcrumb-item active" aria-current="page">
    Editar Curso
  </li>
<% end %>

<div class="card">
  <div class="card-header">
    Rellena el Formulario
  </div>
  <div class="card-body">
    <%= form_for @course do |f| %>
      <%= render partial: 'layouts/errors', locals: {errors: @course.errors }  %>
      <%= render partial: 'form', locals: {course: @course, f: f} %>
      <%= f.submit("Guardar",{class: 'btn btn-primary'})%>
      <%= link_to 'Atrás', courses_path, class: 'btn btn-danger' %>
    <% end %>
  </div>
</div>

<% content_for :scripts do %>

<% end %>

app/views/courses/enrollments.html.erb
<% content_for :breadcrumb do  %>
  <li class="breadcrumb-item active" aria-current="page">
    Inscripciones
  </li>
<% end %>

<div class="row mt-5">
  <div class="col-12">
    <h1>Inscripciones</h1><small>
    <%= @course.name %>
  </small>
  </div>
</div>

<div class="row mt-3">
  <div class="col">
    <div class="form-row">
      <div class="form-group col">
        <%#= label_tag :type_of_meeting_id %>
        <%#= select_tag :type_of_meeting_id, @type_of_meetings.collect{|c| [c.name, c.id]}, {}, {style: 'width: 100%', class: 'custom-select js-custom-select'} %>
      </div>
    </div>
  </div>
</div>

<div class="row">
  <div class="col shadow-sm">
    <table
      data-toggle="table"
      data-search="true"
      data-show-refresh="true"
      data-show-toggle="true"
    >
      <thead>
      <tr>
        <th>Nombre Completo</th>
        <th>Teléfono</th>
        <th>Persona Encargada</th>
        <th>Pagado?</th>
        <th>Total Pagado</th>
        <th>Acciones</th>
      </tr>
      </thead>
      <tbody>
      <% @course.course_enrollments.each do |course_enrollment| %>
        <tr>
          <td><%= course_enrollment.person.full_name %></td>
          <td><%= course_enrollment.person.phone_number %></td>
          <td><%= course_enrollment.person_leader.try(:full_name) %></td>
          <td class="badge badge-info text-white"><%=  course_enrollment.already_paid ? 'Pagado': 'No-Pagado' %></td>
          <td class="badge badge-warning text-white"><%=  number_to_currency(course_enrollment.partial_payment) %></td>
          <td>

          </td>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>


<% content_for :scripts do %>
  <%= javascript_pack_tag 'main-app/src/enrollments/enrollment'%>
<% end %>

app/views/courses/index.html.erb
<% content_for :breadcrumb do  %>
  <li class="breadcrumb-item active" aria-current="page">
    Listado Cursos Activos
  </li>
<% end %>

<div class="d-flex position-absolute" style="bottom: 10%; right: 2%">
  <a  href="<%= new_course_path %>" class="btn shadow btn-lg bg-dark rounded-pill">
    <i class="fas fa-plus text-white"></i>
  </a>
</div>

<div class="row">
  <div class="col shadow-sm">
    <table
      data-toggle="table"
      data-search="true"
      data-show-refresh="true"
      data-show-toggle="true"
    >
      <thead>
      <tr>
        <th>Nombre</th>
        <th>Inscripciónes desde</th>
        <th>Fecha de Inicio</th>
        <th>Mínimo de Personas Inscritas</th>
        <th>Personas Inscritas</th>
        <th>Total Recaudado</th>
        <th>Costo por Persona</th>
        <th>Tipo de Curso</th>
        <th>Acciones</th>
      </tr>
      </thead>
      <tbody>
      <% @courses.each do |course| %>
        <tr>
          <td><%= course.name %></td>
          <td><%= l course.pre_enrollment %></td>
          <td><%= l course.start_date %></td>
          <td><%=  course.min_people %></td>
          <td><%=  course.total_people_inscription %></td>
          <td><%=  number_to_currency(course.total_incoming) %></td>
          <td><%=  number_to_currency(course.amount_by_person) %></td>
          <td><%=  course.type_of_course.try(:name) %></td>
          <td>
            <a href="<%= course_path(course) %>" class="text-primary" data-toggle="tooltip" data-placement="top" title="Tooltip on top">
              <i class="fas fa-eye"></i>
            </a>
            <a href="<%= edit_course_path(course) %>" class="text-primary" data-toggle="tooltip" data-placement="top" title="Tooltip on top">
              <i class="fas fa-edit"></i>
            </a>

            <%= link_to course, method: :delete,"title":"Tooltip on top", "data-placement:":"top","data-toggle": "tooltip" ,class: 'text-danger', data: { confirm: 'Are you sure?' }  do %>
              <i class="fas fa-trash"></i>
            <% end %>
          </td>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/courses/new.html.erb
<% content_for :breadcrumb do  %>
  <li class="breadcrumb-item active" aria-current="page">
    Nuevo Curso
  </li>
<% end %>

<div class="card">
  <div class="card-header">
    Rellena el Formulario
  </div>
  <div class="card-body">
    <%= form_for @course do |f| %>
      <%= render partial: 'layouts/errors', locals: {errors: @course.errors }  %>
      <%= render partial: 'form', locals: {course: @course, f: f} %>
      <%= f.submit("Guardar",{class: 'btn btn-primary'})%>
      <%= link_to 'Atrás', courses_path, class: 'btn btn-danger' %>
    <% end %>
  </div>
</div>

<% content_for :scripts do %>

<% end %>

app/views/courses/show.html.erb
<div class="row mt-5 justify-content-end">
  <div class="btn-toolbar" role="toolbar" aria-label="Herramientas para cursos">
    <div class="btn-group" role="group" aria-label="First group">
      <a role="button" href="<%= enrollments_course_path %>" class="btn btn-info text-white mr-1">
        <i class="fas fa-file mr-2">
          Inscripciones
        </i>
      </a>
      <button type="button" class="btn btn-info">
        <i class="fas fa-book-open">
          Control de Asistencia
        </i>
      </button>

    </div>
  </div>
</div>

<div class="row mt-5">
  <div class="col">
    <div class="card shadow">
      <div class="card-body">
        <div class="row">
          <div class="col">
            <h2>Datos de <%= @course.name %></h2>
          </div>
        </div>
        <div class="row">
          <div class="col col-md-6">
          <span class="font-weight-bold">
            Inicio:
            </span>
            <span class="font-italic">
              <%= l @course.start_date, format: :long %>
            </span>
          </div>
          <div class="col col-md-6">
            <span class="font-weight-bold">
              Fin:
            </span>
            <span class="font-italic">
              <%= l @course.end_date, format: :long %>
            </span>
          </div>
          <div class="col-12 col-md-6">
            <span class="font-weight-bold">
              Pre-Inscripción:
            </span>
            <span class="font-italic">
              <%= l @course.pre_enrollment, format: :long %>
            </span>
          </div>
          <div class="col-12 col-md-12">
            <span class="font-weight-bold">
              Mínimo de Personas:
            </span>
            <span class="font-italic">
              <%= @course.min_people %>
            </span>
          </div>
          <div class="col-12 col-md-12">
            <span class="font-weight-bold">
              Máximo de Personas:
            </span>
            <span class="font-italic">
              <%= @course.max_people %>
            </span>
          </div>
          <div class="col-12 col-md-12">
            <span class="font-weight-bold">
              Personas Inscritas:
            </span>
            <span class="font-italic">
              <%= @course.total_people_inscription %>
            </span>
          </div>
          <div class="col-12 col-md-12">
            <span class="font-weight-bold">
              Se controla asistencia?:
            </span>
            <span class="font-italic">
              <input type="checkbox" <%= @course.attendance_control? ? 'checked' : nil %> disabled>
            </span>
          </div>
          <div class="col-12 col-md-12">
            <span class="font-weight-bold">
              Precio:
            </span>
            <span class="badge badge-primary">
              <%= number_to_currency(@course.amount_by_person) %>
            </span>
          </div>
          <div class="col-12 col-md-12">
            <span class="font-weight-bold">
              Total Recaudado:
            </span>
            <span class="badge badge-success">
              <%= number_to_currency(@course.total_incoming) %>
            </span>
          </div>
          <div class="col-12 col-md-12">
            <span class="font-weight-bold">
              Temas:
            </span>
            <% @course.type_of_course.course_topics.each do |t| %>
              <span class="badge badge-warning">
                <%= t.topic_name  %>
              </span>
            <% end %>
          </div>

          <div class="col-12 col-md-12">
            <span class="font-weight-bold">
              Pre-requisitos:
            </span>
            <% @course.type_of_course.prerequisite_type_of_courses.each do |p| %>
              <span class="badge badge-info">
                <%= p.name  %>
              </span>
            <% end %>
          </div>





          <div class="col-md-12">
            <span class="font-weight-bold">Es viable realizar el curso?</span>

            <span class="badge badge-danger">No</span>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="row mt-2">
  <div class="col-3">
    <a href="<%= courses_path %>" role="button" class="btn btn-outline-primary">
      Volver
    </a>
  </div>
</div>